name: '[CACHE] Data Flow'

on: [workflow_dispatch]

jobs:
  set-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
      
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Handle cache for Python dependencies
        # ðŸ‰ Warning: Do not store sensitive information in the cache (beware of configuration files containing secrets), 
        # as the cache is accessible to anyone who can create a PR on the repository, even on forks.
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        
      - name: Install dependencies if not found in cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

  use-cache:
    runs-on: ubuntu-latest
    needs: set-cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Handle cache for Python dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies if not found in cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
  
  update-cache:
    runs-on: ubuntu-latest
    needs: use-cache
    steps:
      - run:
          echo "boto3==1.34.54" >> requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Handle cache for Python dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      
      - name: Install dependencies if not found in cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt