name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [push-content]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
            path: blog

      - name: Checkout articles
        uses: actions/checkout@v3
        with:
            repository: ${{ secrets.ARTICLES }}
            path: articles
            token: ${{ secrets.BLOG }}

      - name: Move frontend to root
        run: |
            mv blog/* $GITHUB_WORKSPACE/.
            rm -rf blog
            mv articles/personal/* $GITHUB_WORKSPACE/my-website/personal/.
            mv articles/personal_br/* $GITHUB_WORKSPACE/my-website/i18n/pt-BR/docusaurus-plugin-content-blog-personal
            mv articles/tech/* $GITHUB_WORKSPACE/my-website/tech/.
            mv articles/tech_br/* $GITHUB_WORKSPACE/my-website/i18n/pt-BR/docusaurus-plugin-content-blog-tech
            ls -la $GITHUB_WORKSPACE/my-website/personal

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd my-website && npm ci

      - name: Build website
        run: cd my-website && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./my-website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          enable_jekyll: false
